version: '3'

services:
  nginx-dev:
    image: nginx
    container_name: serv-rent-nginx-dev
    ports:
      - '80:80'
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/:/etc/nginx/conf.d/
      - /var/uploads:/var/uploads
    networks:
      - serv-rent-network

  serv-rent-postgres-dev:
    image: postgres
    container_name: serv-rent-postgres-dev
    ports:
      - '5432:5432'
    networks:
      - serv-rent-network
    env_file:
      - ../../.env.development
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  serv-rent-web-dev:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    container_name: serv-rent-web-dev
    env_file:
      - ../../.env.development
    ports:
      - '3001:3000'
    volumes:
      - /var/uploads:/app/uploads
    networks:
      - serv-rent-network

networks:
  serv-rent-network:
    driver: bridge

volumes:
  pgdata:
