version: '3'

services:
  serv-rent-postgres-prod:
    image: postgres
    container_name: serv-rent-postgres-prod
    ports:
      - '5432:5432'
    networks:
      - serv-rent-prod-network
    env_file:
      - ../../.env.production
    restart: always

  serv-rent-web-prod:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: serv-rent-web-prod
    container_name: serv-rent-web-prod
    env_file:
      - ../../.env.production
    ports:
      - '3002:3000'
    networks:
      - serv-rent-prod-network

networks:
  serv-rent-prod-network:
    driver: bridge
